---

# Input:
#
#   _p_current_cp4i_instance  : currently processed instance
#   _p_current_cp4i_cluster   : currently processed cp4i cluster
#
# Global parameter:
#
#  cpd_skip_portable_registry    : if True mirror to target reg, otherwise to portable


# TODO(SJ) Define input paramteres for registries


- name: Mirror images for instance type {{ _p_current_cp4i_instance.type }}
  block:

  - name: Get instance properties and instance type details
    include_role: 
      name: cp4i-instance-props
    # returns:
    # _instance_properties 
    # _instance_type_details  

  # Manifests
  # ---------  
  # oc ibm-pak generate mirror-manifests $CASE_NAME --version $CASE_VERSION $TARGET_REGISTRY  
  # oc ibm-pak generate mirror-manifests ibm-my-cloudpak intermediate-registry.com --version 1.0.0 --final-registry myregistry.com


  # Follow stadard instructions to see what commands are needed....


  when: (_p_current_cp4i_instance.state | default('installed')) == 'installed'  