---
# Input:
#   _p_current_cp4i_cluster
#   _p_current_cp4i_instance
#
# Output
#   _instance_properties


- name: Include version details variables
  include_vars: ../../cp4i-cluster/vars/versions.yml
