---

# Input:
#   cpd_skip_portable_registry    : if True mirror to private reg, otherwise to portable
#



# Find combination of registries

# Start portable registry if needed

# Do mirroring 
# - the registry related variables must be prepared before

- name: Mirror images Cloud Pak for Integration
  include_role:
    name: cp4i-mirror-ibm-pak
  loop: "{{ all_config.cp4i | default([]) }}"
  loop_control:
    loop_var: _p_current_cp4i_cluster

# <-- Add here mirroring other cloud paks that use ibm-pak