---

# Input:
#   cpd_skip_portable_registry    : if True mirror to private reg, otherwise to portable
#


# TODO(SJ) IF NOT cpd_skip_portable_registry THEN start portable registry


- name: Mirror images Cloud Pak for Integration
  include_role:
    name: cp4i-mirror-ibm-pak
  loop: "{{ all_config.cp4i | default([]) }}"
  loop_control:
    loop_var: _p_current_cp4i_cluster

# <-- Add here mirroring other cloud paks that use ibm-pak