---

# Variables:
#   _case_dir
#   current_cp4i_instance
#   current_cp4i_cluster

- name: Create catalog source file for {{ current_cp4i_instance.type }}
  block:

  - name: Find version specific instance type properties
    include_tasks: get-instance-properties.yml

  - name: Get the details for instance type {{ instance_properties.type }}
    set_fact:
      _instance_type_details: "{{ instance_types | json_query(query) | first | default({}) }}"
    vars:
      query: >-
        [?type=='{{ instance_properties.type }}']

  - fail:
      msg: The definition of instance type {{ instance_properties.type }} not found
    when: _instance_type_details=={}

  # -------------------- ENTITLED REGISTRY ----------------------------

  - name: Create catalog source from CASE {{ _instance_type_details.package_name }}-{{ instance_properties.case_version }}
    shell: |
      oc apply -f ~/.ibm-pak/data/mirror/{{ _instance_type_details.package_name }}/{{ instance_properties.case_version }}/catalog-sources.yaml

  # -------------------- PRIVATE REGISTRY -----------------------------

  # __SJ__ - Implement creating catalog source from CASE when private registry is used.
  #          Not needed - alternative implementation is planned

  when: (current_cp4i_instance.state | default('installed')) == 'installed'