---

# INPUT VARIABLES:
# The following variables are prepared in roles 10 and 20:
#
# all_config      : loaded all configuration yamls
# status_dir      : from environment variable STATUS_DIR
# cloud_platform

# PREREQUISITES:
# vault with the entitlement key

#
# State info 
#

- debug:
    msg: "Handling CP4I cluster {{ current_cp4i_cluster.project }}"

#
# Check if license is accepted and fail if it is not
#

- set_fact:
    _cpd_accept_licenses: "False"

- set_fact:
    _cpd_accept_licenses: "True"
  when: (cpd_accept_licenses | default(False) | bool) or (current_cp4i_cluster.accept_licenses | default(False) | bool)

- name: Fail if licenses were not accepted
  fail:
    msg: "You must accept the licenses, either in the cp4i object with accept_licenses: True, or by specifying --accept-all-licenses at the command line"
  when: 
  - not (cpd_accept_licenses | default(False) | bool)
  - not (current_cp4i_cluster.accept_licenses | default(False) | bool)

#
# Detect current openshift cluster from config
#

- set_fact:
    _current_openshift_cluster: "{{ all_config.openshift | json_query(query) | first | default({}) }}"
  vars:
    query: >-
      [?name=='{{ current_cp4i_cluster.openshift_cluster_name }}']

#
# Download OpenShift client for current version
#

- name: Download and activate OpenShift client for version {{ _current_openshift_cluster.ocp_version }}
  include_role:
    name: openshift-download-client
  vars:
    _p_ocp_version: "{{ _current_openshift_cluster.ocp_version }}"

#
# Login to OpenShift cluster
#

- name: Login to the OpenShift cluster
  include_role:
    name: openshift-login
  vars:
    _p_openshift_cluster_name: "{{ current_cp4i_cluster.openshift_cluster_name }}"

#
# Get Entitlement key, 
# fail if it does not exist and local registry is not used
#

- name: Get IBM Entitled Registry key
  include_role: 
    name: vault-get-secret
  vars:
    secret_name: "ibm_cp_entitlement_key"
    secret_group: "{{ environment_name }}"

- set_fact:
    ibm_cp_entitlement_key: "{{ secret_value }}"

- fail:
    msg: "No image registry name specified for CP4I but cannot pull from entitled registry because of missing entitlement key in vault"
  when: ibm_cp_entitlement_key == "" and (current_cp4i_cluster.image_registry_name | default("")) == ""

#
# Prepare credentials for Entitled registry
#

- set_fact:
    entitled_auth: "{{ entitled_registry_username }}:{{ ibm_cp_entitlement_key }}"
  when: ibm_cp_entitlement_key != ""

# 
# Check if Entitled registry is used
#

- set_fact:
    use_entitled_registry: False

- name: Use entitled registry if entitlement key available and no image registry name specified
  set_fact:
    use_entitled_registry: True
  when:
  - (current_cp4i_cluster.image_registry_name | default("")) == ""

#
# If Entitled registry is not used connect to a private registry
#

- name: Connect to private image registry
  include_role: 
    name: connect-private-image-registry
  when: not (use_entitled_registry | bool)

#
# Reset directory for generated files
#

- name: Remove Cloud Pak for Integration directory for generated files
  file:
    path: "{{ status_dir }}/cp4i"
    state: absent

- name: Create Cloud Pak for Integration directory for generated files
  file:
    path: "{{ status_dir }}/cp4i"
    state: directory

#
# Prepare OpenShift cluster
#

- name: Prepare OpenShift cluster for Cloud Pak for Integration
  include_role:
    name: cp4i-prepare-openshift

#
# Run installation
#

- name: Run cp4i installation
  include_tasks: install-cp4i.yml
  when: not (cpd_skip_cp_install | bool)